### PR TITLE
Add the About Package

### PR DESCRIPTION
**Pull request by morucci**
The About package allows to defined a list of Link. The primary
usage is to populate an AboutModal in the Monocle WEB app.

### CODE REVIEW

**Review by TristanCacqueray — COMMENTED** [review]
We might want to have links group instead, e.g.:

```dhall
{
  about : {
    category : {
      name : Text,
      links : List { display_name : Text, url : Text }
    }
  }
}

```

Note that we don't have to split each record attribute into individual file, it might be easier to have a single package for the About config, and we can split it later if needed.

**Comment by morucci** [comment]
@TristanCacqueray well I feel that's OK to have an About package as we have one for SearchAlias. But ok, Link one is probably to much so I've removed it.

Is it ok to merge like that ?

**Comment by morucci** [comment]
It seems if records are not in there own package we get this issue:
```
• ❰Optional a❱ (where ❰a❱ is also a valid nested type)
• Another matching datatype declaration

The Haskell datatype generation logic encountered the following Dhall type:

 ↳ { name : Text, url : Text }
```

So I go back with the previous solution.

**Comment by morucci** [comment]
Updated the monocle submodule within that PR https://github.com/change-metrics/monocle/pull/713
So if that's fine for you I can stash commits there.

**Comment by TristanCacqueray** [comment]
That's ok, but I was also thinking we might want to group links, e.g. `legal`, `doc`, ...
Perhaps we don't need an extra layer and we could use an optional `cat` attribute to the proposed Link.

**Review by TristanCacqueray — APPROVED** [review]

**Comment by morucci** [comment]
@TristanCacqueray  thanks for the suggestion I added the new field and I'll merge this to move forward.

**Pull request merged**
